# Generated by Django 5.1.6 on 2025-03-03 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('search_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('user_ratings_count', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('review_summary', models.TextField(blank=True)),
                ('distance_m', models.IntegerField(blank=True, null=True)),
                ('walking_time_min', models.IntegerField(blank=True, null=True)),
                ('is_best', models.BooleanField(default=False)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='places_api.searchhistory')),
            ],
        ),
    ]
